In [147]:
#import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [148]:
#load data

df=pd.read_excel('Netflix_Unclean_Project.xlsx')

In [149]:
#Check_Data

df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [150]:
df.tail()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [151]:
df.shape

(1013, 20)

In [152]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Title', 'Content_Type', 'Genre',
       'Country', 'Subscription_Plan', 'Device', 'Payment_Method',
       'Account_Status', 'Join_Date', 'Last_Watch_Date', 'Watch_Hours',
       'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating',
       'Monthly_Sessions', 'Download_Count'],
      dtype='str')

In [153]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1013 non-null   str
 1   Customer_Name      1013 non-null   str
 2   Age                1013 non-null   int64
 3   Title              1013 non-null   str
 4   Content_Type       1013 non-null   str
 5   Genre              1010 non-null   str
 6   Country            1013 non-null   str
 7   Subscription_Plan  1013 non-null   str
 8   Device             1009 non-null   str
 9   Payment_Method     1008 non-null   str
 10  Account_Status     1013 non-null   str
 11  Join_Date          1013 non-null   datetime64[us]
 12  Last_Watch_Date    1013 non-null   datetime64[us]
 13  Watch_Hours        1013 non-null   float64
 14  Monthly_Fee        1013 non-null   int64
 15  Movies_Watched     1013 non-null   int64
 16  Episodes_Watched   1013 non-null   int64
 17  Avg_Rating         1013 non-null   float64
 18  Monthly_Sessions   1013 non-null   int64
 19  Download_Count     1013 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(6), str(10)
memory usage: 158.4 KB

In [154]:
#Statstical Analysis

df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1013.000000,1013,1013,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000
mean,42.063179,2023-12-16 10:21:12.260612,2024-11-27 19:59:45.784797,42.417473,436.222113,18.187562,59.834156,3.752419,16.686081,12.472853
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-08 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,31.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-29 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-13 00:00:00,2025-11-14 00:00:00,58.100000,649.000000,27.000000,91.000000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.245811,NaN,NaN,23.988529,214.348252,10.123758,34.895300,0.722812,8.290083,7.577303

In [155]:
#Missing Values

df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [156]:
#Duplicate Records

df.duplicated().sum()

np.int64(5)

In [157]:
df.drop_duplicates(inplace=True)

In [158]:
df.duplicated().sum()

np.int64(0)

In [159]:
#Dirty Values - NA/NULL/Blank/Spaces 

df.replace(
    ['N/A','NULL', '',' '],np.nan,inplace=True
)

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [160]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                4
Country              1
Subscription_Plan    0
Device               4
Payment_Method       7
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [161]:
# Extra Spaces Remove

df=df.apply(lambda x:x.str.strip() if x.dtype == "str" else x)
df.info()

<class 'pandas.DataFrame'>
Index: 1008 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1008 non-null   str
 1   Customer_Name      1008 non-null   str
 2   Age                1008 non-null   int64
 3   Title              1008 non-null   str
 4   Content_Type       1008 non-null   str
 5   Genre              1004 non-null   str
 6   Country            1007 non-null   str
 7   Subscription_Plan  1008 non-null   str
 8   Device             1004 non-null   str
 9   Payment_Method     1001 non-null   str
 10  Account_Status     1008 non-null   str
 11  Join_Date          1008 non-null   datetime64[us]
 12  Last_Watch_Date    1008 non-null   datetime64[us]
 13  Watch_Hours        1008 non-null   float64
 14  Monthly_Fee        1008 non-null   int64
 15  Movies_Watched     1008 non-null   int64
 16  Episodes_Watched   1008 non-null   int64
 17  Avg_Rating         1008 non-null   float64
 18  Monthly_Sessions   1008 non-null   int64
 19  Download_Count     1008 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(6), str(10)
memory usage: 165.4 KB

In [162]:
#Standardize Text

df["Country"] = df["Country"].str.title()

df["Genre"] = (df["Genre"].str.title())

df["Subscription_Plan"] = (df["Subscription_Plan"].str.title())

df["Payment_Method"] = (df["Payment_Method"].str.title())

df["Account_Status"] = (df["Account_Status"].str.title())

In [163]:
#Counting elements

df["Country"].value_counts()

Country
Spain             109
United States     107
Germany           104
Canada            103
United Kingdom    102
Japan             100
France             98
India              97
South Korea        96
Australia          91
Name: count, dtype: int64

In [164]:
 #Numeric columns

numeric_cols=['Age','Watch_Hours','Monthly_Fee','Movies_Watched','Episodes_Watched','Avg_Rating','Monthly_Sessions', 'Download_Count']

In [165]:
for col in numeric_cols:
    df[col]=pd.to_numeric(df[col],errors ='coerce')

In [166]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1008.000000,1008,1008,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,42.097222,2023-12-15 20:42:51.428571,2024-11-28 00:20:00,42.449107,435.960317,18.226190,59.766865,3.751984,16.690476,12.448413
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-07 18:00:00,2023-12-25 12:00:00,25.650000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,54.000000,2024-12-13 00:00:00,2025-11-14 06:00:00,58.100000,649.000000,27.000000,90.250000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.258334,NaN,NaN,24.016448,214.461100,10.099231,34.916046,0.724172,8.287380,7.559714

In [167]:
df=df[(df['Age']>=18) & (df['Age']<=100)]

In [168]:
df['Age'].describe()

count    1003.000000
mean       41.973081
std        13.811906
min        18.000000
25%        30.000000
50%        43.000000
75%        53.500000
max        65.000000
Name: Age, dtype: float64

In [209]:
#Negative Values

df[df['Watch_Hours'] >= 0]
df[df['Monthly_Fee'] >= 0]

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group,Active_Flag
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,...,5,97,3.6,11,3,7139,42.0,Medium,18-25,1
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,5,84,4.5,22,19,3278,41.0,Unknown,36-50,1
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,16,106,3.8,26,3,3874,57.9,Medium,36-50,0
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Medium,36-50,1
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,10,78,3.2,15,20,9735,67.0,Medium,51+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Medium,36-50,1
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,10,78,3.2,15,20,9735,67.0,Medium,51+,1
1010,CUST55547,Customer 656,42,You,Movie,Unknown,Germany,Basic,Mobile,Credit Card,...,32,11,4.5,12,7,1788,62.5,Medium,36-50,0
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,...,19,11,2.8,12,23,7788,77.3,Medium,18-25,1
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,...,14,91,3.5,15,23,7485,57.4,Low,51+,0

In [244]:
df['Watch_Hours'] = df['Watch_Hours'].abs()

df.loc[df['Watch_Hours'] < 0, 'Watch_Hours'] = 0

df = df[df['Watch_Hours'] >= 0]

(df['Watch_Hours'] < 0).sum()

df[df['Watch_Hours'] < 0]['Watch_Hours']

Series([], Name: Watch_Hours, dtype: float64)

In [245]:
#Data Cleaning (date)

df['Join_Date'] =pd.to_datetime(df['Join_Date'],errors='coerce')
df['Last_Watch_Date'] =pd.to_datetime(df['Last_Watch_Date'],errors='coerce')

In [246]:
#Missing Values

df['Age']=df['Age'].fillna(
    df['Age'].mean()
)

df['Watch_Hours']=df['Watch_Hours'].fillna(
    df['Watch_Hours'].mean()
)

df['Monthly_Fee']=df['Monthly_Fee'].fillna(
    df['Monthly_Fee'].mean()
)

In [247]:
df['Payment_Method'] = df['Payment_Method'].fillna("Unknown")
df['Device'] = df['Device'].fillna("Unknown")
df['Genre'] = df['Genre'].fillna("Unknown")

In [248]:
#Feature Engineering

#Customer Revenue

df['Customer_Revenue'] = df['Monthly_Fee'] *df['Monthly_Sessions']

In [249]:
#Engagement Score

df['Engagement_Score'] =(df['Watch_Hours'] + df['Monthly_Sessions'] + df['Download_Count'])

In [250]:
df[df['Watch_Hours'] >= 0]

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group,Active_Flag
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,...,5,97,3.6,11,3,7139,42.0,Medium,18-25,1
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,5,84,4.5,22,19,3278,41.0,Unknown,36-50,1
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,16,106,3.8,26,3,3874,57.9,Medium,36-50,0
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Medium,36-50,1
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,10,78,3.2,15,20,9735,67.0,Medium,51+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Medium,36-50,1
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,10,78,3.2,15,20,9735,67.0,Medium,51+,1
1010,CUST55547,Customer 656,42,You,Movie,Unknown,Germany,Basic,Mobile,Credit Card,...,32,11,4.5,12,7,1788,62.5,Medium,36-50,0
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,...,19,11,2.8,12,23,7788,77.3,Medium,18-25,1
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,...,14,91,3.5,15,23,7485,57.4,Low,51+,0

In [271]:
# Watch Category
df['Watch_Category'] = np.select(
    [
        df['Watch_Hours'] == 0,
        df['Watch_Hours'].between(1, 50),
        df['Watch_Hours'].between(50, 100),
        df['Watch_Hours'] > 100
    ],
    [
        'No Watch',
        'Low',
        'Medium',
        'High'
    ],
    default='Unknown'
)

In [272]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group,Active_Flag
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,Paypal,...,5,97,3.6,11,3,7139,42.0,Low,18-25,1
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,5,84,4.5,22,19,3278,41.0,No Watch,36-50,1
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,16,106,3.8,26,3,3874,57.9,Low,36-50,0
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Low,36-50,1
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,10,78,3.2,15,20,9735,67.0,Low,51+,1

In [273]:
df['Watch_Category'].value_counts().sum()

np.int64(1003)

In [307]:
#Customer Age Group

bins =[17,25,35,50,100]
label =['18-25','26-35','36-50','51+']

df['Age_Group'] =pd.cut(df['Age'],bins =bins ,labels=label)

In [308]:
df['Age_Group'].value_counts()

Age_Group
51+      329
36-50    311
26-35    215
18-25    148
Name: count, dtype: int64

In [309]:
#Account Active Flag

df['Active_Flag'] =np.where(df["Account_Status"]=="Active",1,0)

In [310]:
df.info()

<class 'pandas.DataFrame'>
Index: 1003 entries, 0 to 1012
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1003 non-null   object
 1   Customer_Name      1003 non-null   object
 2   Age                1003 non-null   int64
 3   Title              1003 non-null   object
 4   Content_Type       1003 non-null   object
 5   Genre              1003 non-null   object
 6   Country            1003 non-null   object
 7   Subscription_Plan  1003 non-null   object
 8   Device             1003 non-null   object
 9   Payment_Method     1003 non-null   object
 10  Account_Status     1003 non-null   object
 11  Join_Date          1003 non-null   datetime64[us]
 12  Last_Watch_Date    1003 non-null   datetime64[us]
 13  Watch_Hours        1003 non-null   float64
 14  Monthly_Fee        1003 non-null   int64
 15  Movies_Watched     1003 non-null   int64
 16  Episodes_Watched   1003 non-null   int64
 17  Avg_Rating         1003 non-null   float64
 18  Monthly_Sessions   1003 non-null   int64
 19  Download_Count     1003 non-null   int64
 20  Customer_Revenue   1003 non-null   int64
 21  Engagement_Score   1003 non-null   float64
 22  Watch_Category     1003 non-null   str
 23  Age_Group          1003 non-null   category
 24  Active_Flag        1003 non-null   int64
dtypes: category(1), datetime64[us](2), float64(3), int64(8), object(10), str(1)
memory usage: 197.1+ KB

In [311]:
# Define the columns you want to convert
columns_to_convert = [
    'Customer_ID', 'Customer_Name', 'Title', 'Content_Type', 
    'Genre', 'Country', 'Subscription_Plan', 'Device', 
    'Payment_Method', 'Account_Status'
]

# Create a dictionary mapping each column to the 'object' datatype
conversion_dict = {col: object for col in columns_to_convert}

# Convert the datatypes in your DataFrame
df = df.astype(conversion_dict)

# Verify the changes
print(df.dtypes)

Customer_ID                  object
Customer_Name                object
Age                           int64
Title                        object
Content_Type                 object
Genre                        object
Country                      object
Subscription_Plan            object
Device                       object
Payment_Method               object
Account_Status               object
Join_Date            datetime64[us]
Last_Watch_Date      datetime64[us]
Watch_Hours                 float64
Monthly_Fee                   int64
Movies_Watched                int64
Episodes_Watched              int64
Avg_Rating                  float64
Monthly_Sessions              int64
Download_Count                int64
Customer_Revenue              int64
Engagement_Score            float64
Watch_Category                  str
Age_Group                  category
Active_Flag                   int64
dtype: object

In [312]:
#Final Data Quality Checkup

df.info()

<class 'pandas.DataFrame'>
Index: 1003 entries, 0 to 1012
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1003 non-null   object
 1   Customer_Name      1003 non-null   object
 2   Age                1003 non-null   int64
 3   Title              1003 non-null   object
 4   Content_Type       1003 non-null   object
 5   Genre              1003 non-null   object
 6   Country            1003 non-null   object
 7   Subscription_Plan  1003 non-null   object
 8   Device             1003 non-null   object
 9   Payment_Method     1003 non-null   object
 10  Account_Status     1003 non-null   object
 11  Join_Date          1003 non-null   datetime64[us]
 12  Last_Watch_Date    1003 non-null   datetime64[us]
 13  Watch_Hours        1003 non-null   float64
 14  Monthly_Fee        1003 non-null   int64
 15  Movies_Watched     1003 non-null   int64
 16  Episodes_Watched   1003 non-null   int64
 17  Avg_Rating         1003 non-null   float64
 18  Monthly_Sessions   1003 non-null   int64
 19  Download_Count     1003 non-null   int64
 20  Customer_Revenue   1003 non-null   int64
 21  Engagement_Score   1003 non-null   float64
 22  Watch_Category     1003 non-null   str
 23  Age_Group          1003 non-null   category
 24  Active_Flag        1003 non-null   int64
dtypes: category(1), datetime64[us](2), float64(3), int64(8), object(10), str(1)
memory usage: 197.1+ KB

In [313]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                0
Country              0
Subscription_Plan    0
Device               0
Payment_Method       0
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
Customer_Revenue     0
Engagement_Score     0
Watch_Category       0
Age_Group            0
Active_Flag          0
dtype: int64

In [314]:
df.duplicated().sum()

np.int64(0)

In [315]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Active_Flag
count,1003.000000,1003,1003,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000
mean,41.973081,2023-12-15 07:20:45.463609,2024-11-26 23:08:18.903290,42.485045,436.543370,18.242273,59.723829,3.751346,16.673978,12.449651,7310.470588,71.608674,0.710867
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,0.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000,-4543.000000,11.000000,0.000000
25%,30.000000,2022-12-07 12:00:00,2023-12-25 00:00:00,25.450000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000,2682.000000,50.900000,0.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-02 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000,5841.000000,71.600000,1.000000
75%,53.500000,2024-12-12 00:00:00,2025-11-13 12:00:00,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000,11477.000000,89.800000,1.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000,19470.000000,167.300000,1.000000
std,13.811906,NaN,NaN,23.850055,214.305681,10.092691,34.891084,0.723284,8.285836,7.559756,5369.070148,26.288886,0.453586

In [316]:
df["Country"].isnull().sum()

np.int64(0)

In [317]:
df["Country"] = df["Country"].fillna('Unknown')

In [318]:
df["Country"].isnull().sum()

np.int64(0)

In [319]:
df.info()

<class 'pandas.DataFrame'>
Index: 1003 entries, 0 to 1012
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1003 non-null   object
 1   Customer_Name      1003 non-null   object
 2   Age                1003 non-null   int64
 3   Title              1003 non-null   object
 4   Content_Type       1003 non-null   object
 5   Genre              1003 non-null   object
 6   Country            1003 non-null   object
 7   Subscription_Plan  1003 non-null   object
 8   Device             1003 non-null   object
 9   Payment_Method     1003 non-null   object
 10  Account_Status     1003 non-null   object
 11  Join_Date          1003 non-null   datetime64[us]
 12  Last_Watch_Date    1003 non-null   datetime64[us]
 13  Watch_Hours        1003 non-null   float64
 14  Monthly_Fee        1003 non-null   int64
 15  Movies_Watched     1003 non-null   int64
 16  Episodes_Watched   1003 non-null   int64
 17  Avg_Rating         1003 non-null   float64
 18  Monthly_Sessions   1003 non-null   int64
 19  Download_Count     1003 non-null   int64
 20  Customer_Revenue   1003 non-null   int64
 21  Engagement_Score   1003 non-null   float64
 22  Watch_Category     1003 non-null   str
 23  Age_Group          1003 non-null   category
 24  Active_Flag        1003 non-null   int64
dtypes: category(1), datetime64[us](2), float64(3), int64(8), object(10), str(1)
memory usage: 197.1+ KB

In [320]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Active_Flag
count,1003.000000,1003,1003,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000
mean,41.973081,2023-12-15 07:20:45.463609,2024-11-26 23:08:18.903290,42.485045,436.543370,18.242273,59.723829,3.751346,16.673978,12.449651,7310.470588,71.608674,0.710867
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,0.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000,-4543.000000,11.000000,0.000000
25%,30.000000,2022-12-07 12:00:00,2023-12-25 00:00:00,25.450000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000,2682.000000,50.900000,0.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-02 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000,5841.000000,71.600000,1.000000
75%,53.500000,2024-12-12 00:00:00,2025-11-13 12:00:00,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000,11477.000000,89.800000,1.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000,19470.000000,167.300000,1.000000
std,13.811906,NaN,NaN,23.850055,214.305681,10.092691,34.891084,0.723284,8.285836,7.559756,5369.070148,26.288886,0.453586

In [321]:
#Convert to Excel

df.to_csv("Netflix_Clean_Data2.csv", index=False)

In [322]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:Makrand@localhost/netflix_db2')

In [324]:
df.to_sql(
        'netflix_customers2',
    con = engine,
    if_exists='replace',
index = False)

1003